name: mdlive_healthcare_app_ui

description: A Flutter Health Care mobile application which connects a patient with a certified doctor regardless of where they are or when they need an appointment.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  bottom_nav:
#    path: ../../AndroidStudioProjects/Flutter/packages/bottom_nav
  fontresoft: ^0.0.5
  extensionresoft: ^0.0.5
  cupertino_icons: ^1.0.8
  go_router: ^13.2.4
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.5
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/kenresoft-logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
